{
 "title": "Kafka",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "query": { "query": "label_values(application)" } }
  ]
 },
 "panels": [
  {
   "title": "Consumer Max Time Between Poll",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumer_time_between_poll_max{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Avg Time Between Poll",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumer_time_between_poll_avg{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Poll Idle Ratio Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumer_poll_idle_ratio_avg{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer_request_latency_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_producer_request_latency_avg{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer_outgoing_byte_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "kafka_producer_outgoing_byte_rate{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer_record_send_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "kafka_producer_record_send_rate{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer_request_rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "kafka_producer_request_rate{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer_records_per_request_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "kafka_producer_records_per_request_avg{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer_request_size_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "kafka_producer_request_size_avg{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer_batch_size_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "kafka_producer_batch_size_avg{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer_record_queue_time_avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "kafka_producer_record_queue_time_avg{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer_bufferpool_wait_ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "kafka_producer_bufferpool_wait_ratio{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer_buffer_available_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "kafka_producer_buffer_available_bytes{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer_compression_rate_avg ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "kafka_producer_compression_rate_avg{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}